### ISSUE TITLE
Usage Instructions?

### ISSUE THREAD

**Issue by ashes999** [nadako/vscode-haxe#1]
Hi,

I reached here from the [vscode-haxe-debug](https://github.com/jcward/vscode-hxcpp-debug) repository. Knowing nothing about VS code (and very little about Haxe), how exactly do I use this repository?

**Comment by nadako** [comment]
To be honest, it's just an experiment I done when they opened the extension API. I'd like someone to take over this repository as I don't really have time to work further on it currently. Perhaps I should mention that in the README

**Comment by jcward** [comment]
I might adopt this repo, since it dovetails with my repo. As far as usage, it's the same as my extension -- just place the root folder of this repo (vscode-haxe) in your `.vscode/extensions` directory (also documented on the [vscode website](https://code.visualstudio.com/Docs/extensions/install-extension#_sharing-privately-with-others-sideloading).)

**Comment by jcward** [comment]
@ashes999 @nadako FYI, I've released: https://github.com/jcward/vscode-haxe

It has initial code completion support.

**Comment by nadako** [comment]
Nice! I'll check it out!

**Comment by nadako** [comment]
And will add a link to your repo from the README

**Comment by jcward** [comment]
This is my first time dealing with externs, so I don't suspect it's very pretty. :) I tried to use simn/ts2hx to translate the definitions, but it wasn't working. I then scraped the vscode doc webpage, then made tweaks by script and hand (only for the things I'm using so far.) On top of that, there are some fragile bits that I'm waiting for the Tides project to provide.

But, I think it's a good start. Thanks for your initial footwork, I would have been lost without it.
